### ISSUE TITLE
enableHooks not sufficient if jest config contains "resetMocks: true"

### ISSUE THREAD

**Issue by kaushlakers** [mikeborozdin/jest-react-hooks-shallow#18]
Hello!

This is a really useful library. Thanks for making it. While trying to integrate this, I realized the steps suggested in the docs don't work as expected if the jest config as `resetMocks` set to `true`: https://jestjs.io/docs/en/configuration#resetmocks-boolean

My `setupHooks.js` file:

```js 
import enableHooks from 'jest-react-hooks-shallow';

enableHooks(jest);
```

It seems that the `resetMocks` option clears the mocks setup by this library before every test. I fixed it by using the now deprecated `reenableHooks` function in the following way:

```js
import enableHooks, { reenableHooks } from 'jest-react-hooks-shallow';

enableHooks(jest);

beforeEach(() => {
  reenableHooks();
});
```

I also tried putting just the `enableHooks` in a `beforeEach` block, but didn't seem to work. The above combination is the only thing that worked for me.

I'm wondering if you would consider "re-introducing" the deprecated function since it seems to solve for a particular case? Also, do you mind sharing why it was deprecated?

**Comment by mikeborozdin** [comment]
Hi @kaushlakers,

Thanks a lot for reporting it and apologies for a late response!

It's an interesting situation about `resetMocks`. Once again thank you for investigating the root cause and coming up with a workaround.

Another (non-deprecated workaround) for you is to use a combination of [`{ dontMockByDefault: true; }` and `withHooks()`](https://github.com/mikeborozdin/jest-react-hooks-shallow#option-1----dontmockbydefault-true-).

I've deprecated `reenableHooks()/disableHooks()` because of their very awkward interface. They create dependencies between tests - if you call `disableHooks()` in one test, you'll have to call `reenableHooks()` in the other. It was my quick solution to #12. Then I came up with a more elegant interface of `withHooks()/withoutHooks()` which allows you to wrap test code in a closure and have independent tests.

Anyway, try that. In the meanwhile, I'll look and see if we get the library to work even with `resetMocks: true`.

**Comment by mikeborozdin** [comment]
Hi @kaushlakers ,

Have you tried `withHooks() / withoutHooks()`? Have it solved the problem?

**Comment by kaushlakers** [comment]
Hi @mikeborozdin. Those work but I'd prefer not to have to wrap every single test with `withHooks`. Ideally I want something at the config level,  so I preferred to use the deprecated  API. :)

**Comment by thejuan** [comment]
We are having a simliar issue, we are using `{ dontMockByDefault: true; } and withHooks()`
Our tests that use `mount` also call `resetAllMocks` which resets the useEffect mock to no implementation and breaks the tests

**Comment by mikeborozdin** [comment]
Hi @thejuan ,

Thank you for reporting that! I'll look into that.

**Comment by mikeborozdin** [comment]
> We are having a simliar issue, we are using `{ dontMockByDefault: true; } and withHooks()`
> Our tests that use `mount` also call `resetAllMocks` which resets the useEffect mock to no implementation and breaks the tests

@thejuan,

Is it possible that you provide a code example of that? If you have your test code wrapper inside `withHooks()`, then `resetMocks: true` should not matter.

To be more precise, if you use `mount()` you don't even need to call `withHooks()`. But... if you do have both `resetMocks: true` and tests with `mount()`, then as a workaround you do need to wrap your test inside `withHooks()`.

**Comment by FedericoDiRosa** [comment]
Just upgraded Create React App to version 4 and a bunch of my tests started failing because the main mock is in fact reverted to `undefined` after each test.

Wrapping the `if (dontMockByDefault)` condition in enableHooks with a beforeEach seems to fix the problem but I'm a little concerned about the impact on performance impact if doing that.

On top of that, `withHooks` is implementing a solution that I believe it not supported in Jest 26 anymore? (beforeEach inside a test, see line 14 in mock-use-effect). At least I am getting an error since the update that says _'Hooks cannot be defined inside tests. Hook of type "beforeEach" is nested within ...'_

Now I am thinking, is that part even needed if the main mockImplementation is wrapped inside a beforeEach as suggested above?

**Comment by FedericoDiRosa** [comment]
@mikeborozdin I went ahead an opened a PR, have a look when you can, thanks!

**Comment by mikeborozdin** [comment]
Hi everyone,

This issue has been addressed in version `1.4.2`, so please upgrade.

@FedericoDiRosa, thanks a lot for your PR and sorry for closing it. I used it as an inspiration for my PR where I added the e2e tests.

**Comment by ike18t** [comment]
> 'Hooks cannot be defined inside tests. Hook of type "beforeEach" is nested within ...'

@FedericoDiRosa Did you find a solution/workaround for this issue? I just upgraded CRA and ran into this problem as well.

**Comment by FedericoDiRosa** [comment]
@ike18t Yes I had a workaround but I believe it got lost when my PR was closed. https://github.com/mikeborozdin/jest-react-hooks-shallow/pull/27/commits/0ea696bf9647abb2490648f285b9879d64dc07e3#diff-71521ce9284c7f9fae19af048f19e230b1034eee8d40ea818af7f2733eff7a05L14

See the `beforeEach` I removed there before `previousCalls.clear` was my solution.

@mikeborozdin did you not include that change in the PR intentionally?
